resources:
  - name: dwpdigital-jmx-exporter
    type: registry-image-resource
    source:
      repository: dwpdigital/jmx-exporter
    check_every: 5m

  - name: ecr-dwpdigital-jmx-exporter-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "jmx-exporter"

  - name: ecr-dwpdigital-jmx-exporter
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "jmx-exporter"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-jmx-exporter-dev
    serial_groups: [jmx-exporter]
    plan:
      - get: dwpdigital-jmx-exporter
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-jmx-exporter-dev
        params:
          image: "dwpdigital-jmx-exporter/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-jmx-exporter
    serial_groups: [jmx-exporter]
    plan:
      - get: dwpdigital-jmx-exporter
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-jmx-exporter
        params:
          image: "dwpdigital-jmx-exporter/image.tar"
        attempts: 3
