jobs:
  - name: jmx-exporter-pr
    plan:
      - get: jmx-exporter-pr
        trigger: true
        version: every
      - put: jmx-exporter-pr
        params:
          path: jmx-exporter-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          jmx-exporter: jmx-exporter-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          jmx-exporter: jmx-exporter-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: jmx-exporter-pr
          params:
            path: jmx-exporter-pr
            status: failure
        on_success:
          put: jmx-exporter-pr
          params:
            path: jmx-exporter-pr
            status: success
